### ISSUE TITLE
Wrong link to Linkedin

### ISSUE THREAD

**Issue by rivancic** [datastaxdevs/docker-learning-path#3]
Check following link in week-2 assignment

https://github.com/datastaxdevs/docker-learning-path/blame/master/week-2/README.md#L21

You have to specify markdown link with the protocol like https:// otherwise it links to relative github page.
In your case linkedin links to broken https://github.com/datastaxdevs/docker-learning-path/blob/master/week-2/linkedin.com/in/volochnev

**Comment by HadesArchitect** [comment]
Fixed. Always forgot these `https://` 😅. Thank you!
